name: elvira
description: "Launcher acessível para idosos com suporte offline e assistente pessoal."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # UI e Acessibilidade
  cupertino_icons: ^1.0.8
  google_fonts: ^7.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_svg: ^2.0.10+1

  # Local Database
  sqflite: ^2.3.2
  path_provider: ^2.1.2

  # TTS (Voz Offline) erro de nuget
  #flutter_tts: ^3.8.3

  # Notificações Locais
  flutter_local_notifications: ^19.0.0

  # Permissões
  permission_handler: ^12.0.0

  # Contatos reais do dispositivo
  contacts_service: ^0.6.3

  # Comunicação com WhatsApp (via intents) e etc
  url_launcher: ^6.2.5

  # Controle de Estado (opcional)
  provider: ^6.1.2

  # Leitura de notificações (experimentos futuros)
  receive_sharing_intent: ^1.6.4

  # Outras utilidades
  intl: ^0.20.2
  shared_preferences: ^2.2.2

  connectivity_plus: ^7.0.0
  battery_plus: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/personagens/elvira/
    - assets/audio/
    - assets/fonts/
    - assets/fonts/numbers/
    - assets/icons/

#  fonts:
#    - family: Sora
#      fonts:
#        - asset: assets/fonts/Sora-Regular.ttf
#        - asset: assets/fonts/Sora-Bold.ttf
#        - asset: assets/fonts/Sora-SemiBold.ttf
